export const edgeDistance = '1rem';
export const fontSizeXl = '1.4rem';
export const fontSizeLg = '.9rem';
export const fontSizeMd = '.8rem';
export const fontSizeSm = '.75rem';
export const fontDefault = 'font-weight: 300;'
export const appName = 'Boards';
export const dateFormat = 'DD.MM.YYYY HH:mm:ss';
export const screenWidthMd = '600px';
